"""initial race data schema

Revision ID: 8a464e5bb5c8
Revises: 
Create Date: 2026-09-18 01:02:44.542448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a464e5bb5c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('meeting_name', sa.String(length=255), nullable=True),
    sa.Column('meeting_official_name', sa.Text(), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('circuit_key', sa.Integer(), nullable=True),
    sa.Column('circuit_short_name', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('meeting_key')
    )
    op.create_index(op.f('ix_races_year'), 'races', ['year'], unique=False)
    op.create_table('sessions',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('circuit_short_name', sa.String(length=100), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gmt_offset', sa.String(length=20), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('starting_grid', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['meeting_key'], ['races.meeting_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('ix_sessions_meeting_key'), 'sessions', ['meeting_key'], unique=False)
    op.create_table('drivers',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('name_acronym', sa.String(length=10), nullable=True),
    sa.Column('team_name', sa.String(length=150), nullable=True),
    sa.Column('team_colour', sa.String(length=16), nullable=True),
    sa.Column('headshot_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_key', 'driver_number')
    )
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('duration_sector_1', sa.Float(), nullable=True),
    sa.Column('duration_sector_2', sa.Float(), nullable=True),
    sa.Column('duration_sector_3', sa.Float(), nullable=True),
    sa.Column('i1_speed', sa.Float(), nullable=True),
    sa.Column('i2_speed', sa.Float(), nullable=True),
    sa.Column('st_speed', sa.Float(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=True),
    sa.Column('segments_sector_1', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segments_sector_2', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segments_sector_3', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', 'lap_number', name='uq_lap_session_driver_number')
    )
    op.create_index(op.f('ix_laps_driver_number'), 'laps', ['driver_number'], unique=False)
    op.create_index(op.f('ix_laps_session_key'), 'laps', ['session_key'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lane_duration', sa.Float(), nullable=True),
    sa.Column('stop_duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', 'lap_number', 'date', name='uq_pit_session_driver_lap_date')
    )
    op.create_index(op.f('ix_pit_stops_driver_number'), 'pit_stops', ['driver_number'], unique=False)
    op.create_index(op.f('ix_pit_stops_session_key'), 'pit_stops', ['session_key'], unique=False)
    op.create_table('race_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_race_events_driver_number'), 'race_events', ['driver_number'], unique=False)
    op.create_index(op.f('ix_race_events_event_type'), 'race_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_race_events_meeting_key'), 'race_events', ['meeting_key'], unique=False)
    op.create_index(op.f('ix_race_events_session_key'), 'race_events', ['session_key'], unique=False)
    op.create_index('ix_race_events_session_timestamp', 'race_events', ['session_key', 'timestamp'], unique=False)
    op.create_index(op.f('ix_race_events_timestamp'), 'race_events', ['timestamp'], unique=False)
    op.create_table('stints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(length=30), nullable=True),
    sa.Column('tyre_age_at_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key', 'driver_number', 'stint_number', name='uq_stint_session_driver_number')
    )
    op.create_index(op.f('ix_stints_driver_number'), 'stints', ['driver_number'], unique=False)
    op.create_index(op.f('ix_stints_session_key'), 'stints', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stints_session_key'), table_name='stints')
    op.drop_index(op.f('ix_stints_driver_number'), table_name='stints')
    op.drop_table('stints')
    op.drop_index(op.f('ix_race_events_timestamp'), table_name='race_events')
    op.drop_index('ix_race_events_session_timestamp', table_name='race_events')
    op.drop_index(op.f('ix_race_events_session_key'), table_name='race_events')
    op.drop_index(op.f('ix_race_events_meeting_key'), table_name='race_events')
    op.drop_index(op.f('ix_race_events_event_type'), table_name='race_events')
    op.drop_index(op.f('ix_race_events_driver_number'), table_name='race_events')
    op.drop_table('race_events')
    op.drop_index(op.f('ix_pit_stops_session_key'), table_name='pit_stops')
    op.drop_index(op.f('ix_pit_stops_driver_number'), table_name='pit_stops')
    op.drop_table('pit_stops')
    op.drop_index(op.f('ix_laps_session_key'), table_name='laps')
    op.drop_index(op.f('ix_laps_driver_number'), table_name='laps')
    op.drop_table('laps')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_sessions_meeting_key'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_races_year'), table_name='races')
    op.drop_table('races')
    # ### end Alembic commands ###
